const data = [
  { label: "中国", value: "CN" },
  { label: "中国-香港", value: "HK" },
  { label: "中国-澳门", value: "MO" },
  { label: "中国-台湾", value: "TW" },
  { label: "韩国", value: "KR" },
  { label: "日本", value: "JP" },
  { label: "马来西亚", value: "MY" },
  { label: "缅甸", value: "MM" },
  { label: "菲律宾", value: "PH" },
  { label: "新加坡", value: "SG" },
  { label: "泰国", value: "TH" },
  { label: "越南", value: "VN" },
  { label: "印度", value: "IN" },
  { label: "以色列", value: "IL" },
  { label: "沙特阿拉伯", value: "SA" },
  { label: "土耳其", value: "TR" },
  { label: "哈萨克斯坦", value: "KZ" },
  { label: "美国", value: "US" },
  { label: "加拿大", value: "CA" },
  { label: "墨西哥", value: "MX" },
  { label: "巴西", value: "BR" },
  { label: "芬兰", value: "FI" },
  { label: "瑞典", value: "SE" },
  { label: "挪威", value: "NO" },
  { label: "俄罗斯", value: "RU" },
  { label: "乌克兰", value: "UA" },
  { label: "波兰", value: "PL" },
  { label: "捷克", value: "CZ" },
  { label: "匈牙利", value: "HU" },
  { label: "德国", value: "DE" },
  { label: "奥地利", value: "AT" },
  { label: "瑞士", value: "CH" },
  { label: "英国", value: "GB" },
  { label: "荷兰", value: "NL" },
  { label: "比利时", value: "BE" },
  { label: "卢森堡", value: "LU" },
  { label: "法国", value: "FR" },
  { label: "希腊", value: "GR" },
  { label: "西班牙", value: "ES" },
  { label: "葡萄牙", value: "PT" },
  { label: "埃及", value: "EG" },
  { label: "南非", value: "ZA" },
  { label: "澳大利亚", value: "AU" },
];

export default data;
